apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: front.messages
  description: Plugin jQuery + Bootstrap para exibição de mensagens/erros no front legado.
  tags:
    - coffee-script
    - grunt
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex/front.messages
    vtex.com/platform-flow-id: Shopper#4
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: SYPS45XV
spec:
  system: checkout
  lifecycle: maintenance
  owner: te-0001
  type: library
  dependsOn: []
